name: whazlansaja
description: "UAS Mobile 2 bersama azlansaja"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.3
  # sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json_data_chat_dosen/dosen_chat.json
    - assets/Fauziah Soraya.jpeg
    - assets/gambar_dosen/Azlan, S.Kom., M.Kom.jpg
    - assets/gambar_dosen/Badrul Anwar, S.E., S.Kom., M.Kom..jpg
    - assets/gambar_dosen/Dr. Dicky Nofriansyah, S.Kom., M.Kom..jpg
    - assets/gambar_dosen/Dr. Rudi Gunawan, S.E., M.Si..jpg
    - assets/gambar_dosen/Dra. Sri Kusnasari, M.Hum.jpg
    - assets/gambar_dosen/Drs. Sobirin, S.H., M.Si..jpg
    - assets/gambar_dosen/Hendra Jaya, S.Kom., M.Kom..jpg
    - assets/gambar_dosen/Hendryan Winata, S.Kom., M.Kom..jpg
    - assets/gambar_dosen/Iskandar Zulkarnain, S.T., M.Kom..jpg
    - assets/gambar_dosen/Ismawardi Santoso, S.Pd., MS..jpg
    - assets/gambar_dosen/Muhammad Dahria, S.E., S.Kom., M.Kom..jpg
    - assets/gambar_dosen/Muhammad Syahril, SE., M.Kom..jpg
    - assets/gambar_dosen/Mukhlis Ramadhan, S.E., M.Kom..jpg
    - assets/gambar_dosen/Rini Kustini, S.S., MS..jpg
    - assets/gambar_dosen/Saiful Nur Arif, S.E., S.Kom., M.Kom..jpg
    - assets/gambar_dosen/Zulkifli Lubis, S.E., MM..jpg
